version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-nest2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - "5432:5432"  # Expose the PostgreSQL port

  nestjs:
    build: .  # Replace with the path to your NestJS app in the host machine
    container_name: nestjs-task-management
    depends_on:
      - postgres
    environment:
     STAGE: prod
    ports:
      - "3000:3000"  # Expose the NestJS app port
